"""Change structure operation.

Revision ID: 8e68777db77f
Revises: f456967e803f
Create Date: 2024-11-16 00:00:13.444641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e68777db77f"
down_revision: Union[str, None] = "f456967e803f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operations",
        sa.Column(
            "operation_type",
            sa.SmallInteger(),
            nullable=False,
            comment="0 - income, 1 - expense, 2 - investment",
        ),
    )
    op.drop_column("operations", "is_income")
    op.create_check_constraint(
        "operation_type_check",
        "operations",
        condition="operation_type IN (0, 1, 2)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operations",
        sa.Column(
            "is_income", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("operations", "operation_type")
    op.drop_constraint("operation_type_check", "operations", type_="check")
    # ### end Alembic commands ###
