"""Transaction table.

Revision ID: 0dd427d1acd9
Revises: cb78897a4f9b
Create Date: 2024-11-09 17:41:11.393508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dd427d1acd9"
down_revision: Union[str, None] = "cb78897a4f9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("currency_id", sa.UUID(), nullable=False),
        sa.Column("currency_name", sa.String(length=64), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("currency_symbol", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("currency_id"),
    )
    op.create_index(
        op.f("ix_currencies_currency_code"),
        "currencies",
        ["currency_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_currencies_currency_name"),
        "currencies",
        ["currency_name"],
        unique=False,
    )
    op.create_table(
        "operations",
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("operation_name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("operation_id"),
    )
    op.create_index(
        op.f("ix_operations_operation_name"),
        "operations",
        ["operation_name"],
        unique=True,
    )
    op.create_table(
        "categories",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("category_name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.operation_id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("category_id"),
        sa.UniqueConstraint("operation_id", "category_name"),
    )
    op.create_index(
        op.f("ix_categories_category_name"),
        "categories",
        ["category_name"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("currency_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.currency_id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_index(op.f("ix_categories_category_name"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(
        op.f("ix_operations_operation_name"), table_name="operations"
    )
    op.drop_table("operations")
    op.drop_index(op.f("ix_currencies_currency_name"), table_name="currencies")
    op.drop_index(op.f("ix_currencies_currency_code"), table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
