"""Update operations.

Revision ID: f456967e803f
Revises: 0dd427d1acd9
Create Date: 2024-11-14 21:10:44.678523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f456967e803f"
down_revision: Union[str, None] = "0dd427d1acd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operations", sa.Column("is_income", sa.Boolean(), nullable=False)
    )
    op.create_check_constraint(
        "amount_positive", "transactions", condition="amount > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operations", "is_income")
    op.drop_constraint("amount_positive", "transactions", type_="check")
    # ### end Alembic commands ###
